class ErroHoraInvalida(Exception):
    ...

class ErroMinutoInvalido(Exception):
    ...

class ErroSegundoInvalido(Exception):
    ...

class ErroAlarmeHoraInvalida(Exception):
    ...

class ErroAlarmeMinutoInvalido(Exception):
    ...
